services:
  stayforge:
    image: tokujunsystem/stayforge:latest
    container_name: stayforge
    ports:
      - "80:80"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
    networks:
      - database
      - redis

  redis:
    image: redis:latest
    container_name: redis
    #    volumes:
    #      - redis
    networks:
      - redis


  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - database

networks:
  database:
    internal: true
  redis:
    internal: true
volumes:
  data: