services:
  stayforge:
    build:
      context: .
    container_name: stayforge
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=$MONGO_URL
      - REDIS_URL=$REDIS_URL
    depends_on:
      - mongodb
    networks:
      - web
      - database
      - redis

  redis:
    image: redis:latest
    container_name: redis
    #    volumes:
    #      - redis
    networks:
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - database

networks:
  web:
  database:
    internal: true
  redis:
    internal: true
volumes:
  data:
  redis: