services:
  stayforge:
    build:
      context: .
    #    image: tokujunsystem/stayforge:latest
    container_name: stayforge
    ports:
      - "80:80"
    environment:
      - MONGO_URL=$MONGO_URL
      - REDIS_URL=$REDIS_URL
    depends_on:
      - mongodb
    networks:
      - database

  redis:
    image: redis:latest
    container_name: redis
    #    volumes:
    #      - redis
    networks:
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - database

networks:
  database:
    internal: true
  redis:
    internal: true
volumes:
  data:
  redis: