services:
  stayforge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    networks:
      - database

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - database

networks:
  database:
    internal: true
volumes:
  data: