services:
  stayforge:
    build:
      context: .
    container_name: stayforge
    ports:
      - "${PORT:-80}:${PORT:-80}"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-80}
      - WORKERS=${WORKERS:-4}
      - MONGO_URL=$MONGO_URL
      - REDIS_URL=$REDIS_URL
    depends_on:
      - mongodb
    networks:
      - web
      - database
      - redis

  redis:
    image: redis:latest
    container_name: redis
#    volumes:
#      - redis
    networks:
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/auth_db
    networks:
      - database

networks:
  web:
  database:
    internal: true
#  redis:
#    internal: true
volumes:
  data:
#  redis:
