apiVersion: apps/api_factory-dev
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: stayforge
  name: stayforge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stayforge
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: stayforge
    spec:
      containers:
        - env:
            - name: HOST
              value: 0.0.0.0
            - name: MONGO_URL
            - name: PORT
              value: "80"
            - name: REDIS_URL
            - name: WORKERS
              value: "4"
          image: tokujunsystem/stayforge
          name: stayforge
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
