name: Update Wiki Documentation

on:
  push:
    paths:
      - .github/workflows/documents.yml
      - docs/wiki/**

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Push Documentation to Stayforge.wiki
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://github.com/tokujun-t/Stayforge.wiki.git Stayforge.wiki

          cp -r docs/wiki/* Stayforge.wiki/

          cd Stayforge.wiki
          git add .
          git commit -m "Update Wiki Documentation [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tokujun-t/Stayforge.wiki.git
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}