name: Update Wiki Documentation

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/documents.yml
      - docs/wiki/**

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Push Documentation to Stayforge.wiki
        run: |
          git config --global user.name "Tokujunsystems-BOT"
          git config --global user.email "190532409+Tokujunsystems-BOT@users.noreply.github.com"
          git clone https://x-access-token:${BOT_PAT}@github.com/tokujun-t/Stayforge.wiki.git Stayforge.wiki

          cp -r docs/wiki/* Stayforge.wiki/

          cd Stayforge.wiki
          git add .
          git commit -m "Update Python SDK [skip ci]" || echo "No changes to commit"
          git push origin master
        env:
          BOT_PAT: ${{ secrets.BOT_PAT }}
