name: Generate OpenAPI and Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-openapi:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyyaml aiofiles Deprecated

      - name: Generate OpenAPI spec
        run: python openapi.py

      - name: Extract version from tag
        id: extract
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

  build-docker:
    needs: build-openapi
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.build-openapi.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag stayforge/stayforge:${{ needs.build-openapi.outputs.version }} \
            --load

  release-openapi:
    needs: build-openapi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload OpenAPI spec to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: .openapi_spec/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docker:
    needs: [build-openapi, build-docker]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag stayforge/stayforge:${{ needs.build-openapi.outputs.version }} \
                     stayforge/stayforge:${{ needs.build-openapi.outputs.version }}
          docker push stayforge/stayforge:${{ needs.build-openapi.outputs.version }}