name: 'Update API Documents'

on:
  push:
    branches:
      - '**'


jobs:
  wiki:
    runs-on: ubuntu-latest

    steps:
      # Check out source repository
      - name: Checkout source repository
        uses: actions/checkout@v3

      # Get the current branch name and tag
      - name: Get current branch name and tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then

            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
            echo "TAG=" >> $GITHUB_ENV  # 清空 TAG
            echo "No version tag found for branch '${BRANCH_NAME}'"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then

            TAG=${GITHUB_REF#refs/tags/}
            echo "TAG=${TAG}" >> $GITHUB_ENV
          else

            echo "No valid ref found, skipping version assignment."
            echo "TAG=" >> $GITHUB_ENV
          fi

          echo "Generated TAG=${TAG}"

      # Install Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Python version used

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      # Install Redocly CLI
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      # Generate OpenAPI JSON
      - name: Generate OpenAPI JSON
        run: |
          python app.py

      # Update package version in config.yaml
      - name: Update package version in config.yaml
        run: |
          if [[ -f ".github/openapi/config.yaml" ]]; then
            sed -i "s/^packageVersion:.*$/packageVersion: ${TAG}/" .github/openapi/config.yaml
          else
            echo "Error: .github/openapi/config.yaml not found!"
            exit 1
          fi

      #  Check out Wiki repository
      - name: Clone Wiki repository
        run: |
          git clone https://github.com/tokujun-t/Stayforge.wiki.git wiki

      - name: Convert OpenAPI JSON to Markdown
        run: |
          mkdir -p wiki/api-docs
          redocly bundle openapi.json --output wiki/api-docs/api.md

      # Push updates to Wiki repository
      - name: Push updates to Wiki
        run: |
          cd wiki
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update API documentation"
          git push

#  push:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      statuses: write
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#      - name: Install dependencies
#        run: |
#          pip install --no-cache-dir -r requirements.txt
#      - name: Generate OpenAPI JSON
#        run: |
#          python app.py
#      - name: 'Push files and wait for deployment'
#        uses: redocly/reunite-push-action@v1
#        with:
#          organization: 'tokujunsystems'
#          project: 'stayforge'
#          mountPath: '/'
#          files: '/'
#          domain: 'https://app.cloud.redocly.com'
#        env:
#          REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_AUTHORIZATION }}
